// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type UserLoginReply struct {
	Token string `json:"token"`
}

type UserLoginRequest struct {
	UserName string `json:"username"`
	PassWord string `json:"password"`
}
