// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          []byte                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAuthRequest) Reset() {
	*x = OpenAuthRequest{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAuthRequest) ProtoMessage() {}

func (x *OpenAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAuthRequest.ProtoReflect.Descriptor instead.
func (*OpenAuthRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *OpenAuthRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type OpenAuthReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAuthReply) Reset() {
	*x = OpenAuthReply{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAuthReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAuthReply) ProtoMessage() {}

func (x *OpenAuthReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAuthReply.ProtoReflect.Descriptor instead.
func (*OpenAuthReply) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

type UserAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAuthRequest) Reset() {
	*x = UserAuthRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuthRequest) ProtoMessage() {}

func (x *UserAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuthRequest.ProtoReflect.Descriptor instead.
func (*UserAuthRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserAuthRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UserAuthReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Id            uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Extend        map[string]string      `protobuf:"bytes,3,rep,name=extend,proto3" json:"extend,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAuthReply) Reset() {
	*x = UserAuthReply{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAuthReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuthReply) ProtoMessage() {}

func (x *UserAuthReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuthReply.ProtoReflect.Descriptor instead.
func (*UserAuthReply) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserAuthReply) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *UserAuthReply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserAuthReply) GetExtend() map[string]string {
	if x != nil {
		return x.Extend
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\"%\n" +
	"\x0fOpenAuthRequest\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\"\x0f\n" +
	"\rOpenAuthReply\"'\n" +
	"\x0fUserAuthRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xaf\x01\n" +
	"\rUserAuthReply\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\x127\n" +
	"\x06extend\x18\x03 \x03(\v2\x1f.user.UserAuthReply.ExtendEntryR\x06extend\x1a9\n" +
	"\vExtendEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012r\n" +
	"\x04User\x122\n" +
	"\x04Auth\x12\x15.user.UserAuthRequest\x1a\x13.user.UserAuthReply\x126\n" +
	"\bOpenAuth\x12\x15.user.OpenAuthRequest\x1a\x13.user.OpenAuthReplyB\bZ\x06./userb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_user_proto_goTypes = []any{
	(*OpenAuthRequest)(nil), // 0: user.OpenAuthRequest
	(*OpenAuthReply)(nil),   // 1: user.OpenAuthReply
	(*UserAuthRequest)(nil), // 2: user.UserAuthRequest
	(*UserAuthReply)(nil),   // 3: user.UserAuthReply
	nil,                     // 4: user.UserAuthReply.ExtendEntry
}
var file_user_proto_depIdxs = []int32{
	4, // 0: user.UserAuthReply.extend:type_name -> user.UserAuthReply.ExtendEntry
	2, // 1: user.User.Auth:input_type -> user.UserAuthRequest
	0, // 2: user.User.OpenAuth:input_type -> user.OpenAuthRequest
	3, // 3: user.User.Auth:output_type -> user.UserAuthReply
	1, // 4: user.User.OpenAuth:output_type -> user.OpenAuthReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
