// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: device.proto

package server

import (
	"context"

	"new_iot/device/internal/logic"
	"new_iot/device/internal/svc"
	"new_iot/device/types/device"
)

type DeviceServer struct {
	svcCtx *svc.ServiceContext
	device.UnimplementedDeviceServer
}

func NewDeviceServer(svcCtx *svc.ServiceContext) *DeviceServer {
	return &DeviceServer{
		svcCtx: svcCtx,
	}
}

func (s *DeviceServer) SendMessage(ctx context.Context, in *device.SendMessageRequest) (*device.SendMessageReply, error) {
	l := logic.NewSendMessageLogic(ctx, s.svcCtx)
	return l.SendMessage(in)
}
